### ISSUE TITLE
Duda en tarea 

### ISSUE THREAD

**Issue by Pablorv** [lbenet/2017-1_TSFisComp#1]
Hola Uriel! Sofía y yo hicimos lo que Luis pidió en clase del archivo.  Sin embargo en el mismo, además de notar la peculiaridad qué sucede cuando los dos modificamos al mismo tiempo con diferentes commits, también practicamos varias veces cómo actualizar "adecuadamente" en el mismo archivo.
¿Lo ponemos en pull request tal cual? 
Gracias!

**Comment by UriAceves** [comment]
Sí, póngalo en el _pull request_ y yo reviso qué pasó.

**Comment by UriAceves** [comment]
La duda fue resuelta. Cierro el issue.
