### ISSUE TITLE
Problema 1 de la tarea 2

### ISSUE THREAD

**Issue by Oscarhg42** [lbenet/2017-1_TSFisComp#57]
Saludos Luis. Aun no he podido graficar el conjunto de Julia del problema 2. Ya lo estuve atacando desde varias perspectivas (graficar la norma de la malla final, usar el angulo polar, ó imshow(parte imaginaria) ó imshow(parte real) pero sigo obteniendo pantallazos azules execpto con  20 iteraciones como comentaba Claudio el otro día. Todo parece diverger de manera muy muy rápida.

**Comment by lbenet** [comment]
Gracias por el comentario; me recordó que tenía algo que hacer... 

Chequé los cálculos y, _en efecto_, me equivoqué en el valor de la constante en el mapeo cuadrático. Acabo de subir a `master` un nuevo notebook `Tarea2.ipynb`, donde está otro valor, que ahora sí chequé. Mil disculpas.

Cc: @UriAceves @ferjefte @cutsof @Nogarx @rodoart @salvadoragustin @CarolinaLMH @danmarurr @cpierard  @miguelraz @Pablorv @Yuriyama

**Comment by lbenet** [comment]
Tips: (1) Tienen que ver cuántas soluciones distintas hay; (2) `imshow` hace la vida más sencilla.

**Comment by Oscarhg42** [comment]
Gracias Luis. Ahorita lo reviso!

**Comment by lbenet** [comment]
Cierro esto, ya que la fecha de entrega pasó.
